apiVersion: v1
kind: Service
metadata:
  name: payment-services
  labels:
    app: payment-services
spec:
  type: ClusterIP # <-- This is correct
  selector:
    app: payment-services
  ports:
    - port: 3002
      targetPort: 3002