# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: payment-services
# spec:
#   selector:
#     app: payment-services
#   ports:
#     - port: 3002
#       targetPort: 3002
#       nodePort: 30080
#   type: NodePort

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-services
  labels:
    app: payment-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-services
  template:
    metadata:
      labels:
        app: payment-services
    spec:
      containers:
        - name: payment-services
          image: tarsi/payment-services:latest # <-- your built image
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-services
  labels:
    app: payment-services
spec:
  selector:
    app: payment-services
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
