apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  type: ClusterIP
  selector:
    app: product-service # <-- Make sure this matches your product-deploy.yaml
  ports:
    - port: 3001
      targetPort: 3001